// Code generated by protoc-gen-go. DO NOT EDIT.
// source: core.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Value struct {
	Scope                string               `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	Key                  string               `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte               `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Revision             uint64               `protobuf:"varint,5,opt,name=revision,proto3" json:"revision,omitempty"`
	Hash                 []byte               `protobuf:"bytes,7,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Value) Reset()         { *m = Value{} }
func (m *Value) String() string { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()    {}
func (*Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{0}
}

func (m *Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Value.Unmarshal(m, b)
}
func (m *Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Value.Marshal(b, m, deterministic)
}
func (m *Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Value.Merge(m, src)
}
func (m *Value) XXX_Size() int {
	return xxx_messageInfo_Value.Size(m)
}
func (m *Value) XXX_DiscardUnknown() {
	xxx_messageInfo_Value.DiscardUnknown(m)
}

var xxx_messageInfo_Value proto.InternalMessageInfo

func (m *Value) GetScope() string {
	if m != nil {
		return m.Scope
	}
	return ""
}

func (m *Value) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Value) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Value) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Value) GetRevision() uint64 {
	if m != nil {
		return m.Revision
	}
	return 0
}

func (m *Value) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type Snapshot struct {
	Time                 *timestamp.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Snapshot) Reset()         { *m = Snapshot{} }
func (m *Snapshot) String() string { return proto.CompactTextString(m) }
func (*Snapshot) ProtoMessage()    {}
func (*Snapshot) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{1}
}

func (m *Snapshot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Snapshot.Unmarshal(m, b)
}
func (m *Snapshot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Snapshot.Marshal(b, m, deterministic)
}
func (m *Snapshot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Snapshot.Merge(m, src)
}
func (m *Snapshot) XXX_Size() int {
	return xxx_messageInfo_Snapshot.Size(m)
}
func (m *Snapshot) XXX_DiscardUnknown() {
	xxx_messageInfo_Snapshot.DiscardUnknown(m)
}

var xxx_messageInfo_Snapshot proto.InternalMessageInfo

func (m *Snapshot) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

type SetRequest struct {
	Scope                string   `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetRequest) Reset()         { *m = SetRequest{} }
func (m *SetRequest) String() string { return proto.CompactTextString(m) }
func (*SetRequest) ProtoMessage()    {}
func (*SetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{2}
}

func (m *SetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetRequest.Unmarshal(m, b)
}
func (m *SetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetRequest.Marshal(b, m, deterministic)
}
func (m *SetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetRequest.Merge(m, src)
}
func (m *SetRequest) XXX_Size() int {
	return xxx_messageInfo_SetRequest.Size(m)
}
func (m *SetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetRequest proto.InternalMessageInfo

func (m *SetRequest) GetScope() string {
	if m != nil {
		return m.Scope
	}
	return ""
}

func (m *SetRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *SetRequest) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type GetRequest struct {
	Scope                string   `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Revision             uint64   `protobuf:"varint,3,opt,name=revision,proto3" json:"revision,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{3}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetScope() string {
	if m != nil {
		return m.Scope
	}
	return ""
}

func (m *GetRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *GetRequest) GetRevision() uint64 {
	if m != nil {
		return m.Revision
	}
	return 0
}

type DeleteRequest struct {
	Scope                string   `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{4}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetScope() string {
	if m != nil {
		return m.Scope
	}
	return ""
}

func (m *DeleteRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type ListRequest struct {
	Scope                string   `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	Prefix               string   `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{5}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

func (m *ListRequest) GetScope() string {
	if m != nil {
		return m.Scope
	}
	return ""
}

func (m *ListRequest) GetPrefix() string {
	if m != nil {
		return m.Prefix
	}
	return ""
}

type RollbackRequest struct {
	Scope                string               `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	Key                  string               `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Time                 *timestamp.Timestamp `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RollbackRequest) Reset()         { *m = RollbackRequest{} }
func (m *RollbackRequest) String() string { return proto.CompactTextString(m) }
func (*RollbackRequest) ProtoMessage()    {}
func (*RollbackRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{6}
}

func (m *RollbackRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RollbackRequest.Unmarshal(m, b)
}
func (m *RollbackRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RollbackRequest.Marshal(b, m, deterministic)
}
func (m *RollbackRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RollbackRequest.Merge(m, src)
}
func (m *RollbackRequest) XXX_Size() int {
	return xxx_messageInfo_RollbackRequest.Size(m)
}
func (m *RollbackRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RollbackRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RollbackRequest proto.InternalMessageInfo

func (m *RollbackRequest) GetScope() string {
	if m != nil {
		return m.Scope
	}
	return ""
}

func (m *RollbackRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *RollbackRequest) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

type RollbackResult struct {
	AffectedRows         uint64   `protobuf:"varint,1,opt,name=affected_rows,json=affectedRows,proto3" json:"affected_rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RollbackResult) Reset()         { *m = RollbackResult{} }
func (m *RollbackResult) String() string { return proto.CompactTextString(m) }
func (*RollbackResult) ProtoMessage()    {}
func (*RollbackResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{7}
}

func (m *RollbackResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RollbackResult.Unmarshal(m, b)
}
func (m *RollbackResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RollbackResult.Marshal(b, m, deterministic)
}
func (m *RollbackResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RollbackResult.Merge(m, src)
}
func (m *RollbackResult) XXX_Size() int {
	return xxx_messageInfo_RollbackResult.Size(m)
}
func (m *RollbackResult) XXX_DiscardUnknown() {
	xxx_messageInfo_RollbackResult.DiscardUnknown(m)
}

var xxx_messageInfo_RollbackResult proto.InternalMessageInfo

func (m *RollbackResult) GetAffectedRows() uint64 {
	if m != nil {
		return m.AffectedRows
	}
	return 0
}

type HashRequest struct {
	Scope                string   `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Revision             uint64   `protobuf:"varint,3,opt,name=revision,proto3" json:"revision,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HashRequest) Reset()         { *m = HashRequest{} }
func (m *HashRequest) String() string { return proto.CompactTextString(m) }
func (*HashRequest) ProtoMessage()    {}
func (*HashRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{8}
}

func (m *HashRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HashRequest.Unmarshal(m, b)
}
func (m *HashRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HashRequest.Marshal(b, m, deterministic)
}
func (m *HashRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HashRequest.Merge(m, src)
}
func (m *HashRequest) XXX_Size() int {
	return xxx_messageInfo_HashRequest.Size(m)
}
func (m *HashRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HashRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HashRequest proto.InternalMessageInfo

func (m *HashRequest) GetScope() string {
	if m != nil {
		return m.Scope
	}
	return ""
}

func (m *HashRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *HashRequest) GetRevision() uint64 {
	if m != nil {
		return m.Revision
	}
	return 0
}

type HashResponse struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Revision             uint64   `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HashResponse) Reset()         { *m = HashResponse{} }
func (m *HashResponse) String() string { return proto.CompactTextString(m) }
func (*HashResponse) ProtoMessage()    {}
func (*HashResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{9}
}

func (m *HashResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HashResponse.Unmarshal(m, b)
}
func (m *HashResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HashResponse.Marshal(b, m, deterministic)
}
func (m *HashResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HashResponse.Merge(m, src)
}
func (m *HashResponse) XXX_Size() int {
	return xxx_messageInfo_HashResponse.Size(m)
}
func (m *HashResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HashResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HashResponse proto.InternalMessageInfo

func (m *HashResponse) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *HashResponse) GetRevision() uint64 {
	if m != nil {
		return m.Revision
	}
	return 0
}

func init() {
	proto.RegisterType((*Value)(nil), "api.Value")
	proto.RegisterType((*Snapshot)(nil), "api.Snapshot")
	proto.RegisterType((*SetRequest)(nil), "api.SetRequest")
	proto.RegisterType((*GetRequest)(nil), "api.GetRequest")
	proto.RegisterType((*DeleteRequest)(nil), "api.DeleteRequest")
	proto.RegisterType((*ListRequest)(nil), "api.ListRequest")
	proto.RegisterType((*RollbackRequest)(nil), "api.RollbackRequest")
	proto.RegisterType((*RollbackResult)(nil), "api.RollbackResult")
	proto.RegisterType((*HashRequest)(nil), "api.HashRequest")
	proto.RegisterType((*HashResponse)(nil), "api.HashResponse")
}

func init() { proto.RegisterFile("core.proto", fileDescriptor_f7e43720d1edc0fe) }

var fileDescriptor_f7e43720d1edc0fe = []byte{
	// 456 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x51, 0x6b, 0x13, 0x41,
	0x10, 0xe6, 0x72, 0x7b, 0x31, 0x9d, 0xa4, 0xb6, 0xae, 0x45, 0x8e, 0x7b, 0x31, 0xac, 0x28, 0x01,
	0xe1, 0x2a, 0x95, 0x22, 0x2a, 0x08, 0x8a, 0x10, 0x11, 0x1f, 0x74, 0x23, 0x3e, 0xf8, 0x22, 0x9b,
	0x73, 0xd2, 0x2c, 0xbd, 0x66, 0xd7, 0xdb, 0x4d, 0xab, 0xaf, 0xfe, 0x22, 0x7f, 0xa2, 0xec, 0xee,
	0x5d, 0x72, 0x29, 0x52, 0x0d, 0xf6, 0x6d, 0xe7, 0xbb, 0x6f, 0xe6, 0xdb, 0xf9, 0x66, 0x6e, 0x01,
	0x0a, 0x55, 0x61, 0xae, 0x2b, 0x65, 0x15, 0x8d, 0x85, 0x96, 0xd9, 0xdd, 0x13, 0xa5, 0x4e, 0x4a,
	0x3c, 0xf4, 0xd0, 0x74, 0x39, 0x3b, 0xb4, 0xf2, 0x0c, 0x8d, 0x15, 0x67, 0x3a, 0xb0, 0xd8, 0xaf,
	0x08, 0x92, 0x4f, 0xa2, 0x5c, 0x22, 0x3d, 0x80, 0xc4, 0x14, 0x4a, 0x63, 0x1a, 0x0d, 0xa3, 0xd1,
	0x0e, 0x0f, 0x01, 0xdd, 0x87, 0xf8, 0x14, 0x7f, 0xa4, 0x1d, 0x8f, 0xb9, 0xa3, 0xe3, 0x9d, 0xbb,
	0x84, 0x34, 0x1e, 0x46, 0xa3, 0x01, 0x0f, 0x01, 0x7d, 0x0a, 0x50, 0x54, 0x28, 0x2c, 0x7e, 0xfd,
	0x22, 0x6c, 0x4a, 0x86, 0xd1, 0xa8, 0x7f, 0x94, 0xe5, 0x41, 0x3d, 0x6f, 0xd4, 0xf3, 0x8f, 0x8d,
	0x3a, 0xdf, 0xa9, 0xd9, 0x2f, 0x2d, 0xcd, 0xa0, 0x57, 0xe1, 0xb9, 0x34, 0x52, 0x2d, 0xd2, 0x64,
	0x18, 0x8d, 0x08, 0x5f, 0xc5, 0x94, 0x02, 0x99, 0x0b, 0x33, 0x4f, 0x6f, 0x78, 0x2d, 0x7f, 0x66,
	0xcf, 0xa0, 0x37, 0x59, 0x08, 0x6d, 0xe6, 0xca, 0xd2, 0x1c, 0x88, 0xeb, 0xc8, 0xdf, 0xf9, 0x6a,
	0x41, 0xcf, 0x63, 0x6f, 0x01, 0x26, 0x68, 0x39, 0x7e, 0x5b, 0xa2, 0xb1, 0xff, 0xd7, 0x32, 0x7b,
	0x0f, 0x30, 0xde, 0xbe, 0x56, 0xbb, 0xdb, 0x78, 0xb3, 0x5b, 0xf6, 0x04, 0x76, 0x5f, 0x63, 0x89,
	0x16, 0xb7, 0x2c, 0xca, 0x9e, 0x43, 0xff, 0x9d, 0x34, 0x7f, 0xb9, 0xcb, 0x1d, 0xe8, 0xea, 0x0a,
	0x67, 0xf2, 0x7b, 0x9d, 0x59, 0x47, 0x4c, 0xc2, 0x1e, 0x57, 0x65, 0x39, 0x15, 0xc5, 0xe9, 0xb6,
	0xcd, 0x34, 0xf6, 0x93, 0x7f, 0xb4, 0xff, 0x18, 0x6e, 0xae, 0xa5, 0xcc, 0xb2, 0xb4, 0xf4, 0x1e,
	0xec, 0x8a, 0xd9, 0x0c, 0x0b, 0xb7, 0x38, 0x95, 0xba, 0x30, 0x5e, 0x91, 0xf0, 0x41, 0x03, 0x72,
	0x75, 0x61, 0xd8, 0x07, 0xe8, 0xbf, 0x11, 0x66, 0x7e, 0x9d, 0x56, 0xbf, 0x80, 0x41, 0x28, 0x69,
	0xb4, 0x5a, 0x18, 0x5c, 0x2d, 0x5a, 0xb4, 0x5e, 0xb4, 0x8d, 0xfc, 0xce, 0x66, 0xfe, 0xd1, 0xcf,
	0x0e, 0x24, 0x13, 0x2b, 0x2c, 0x52, 0x06, 0xf1, 0x04, 0x2d, 0xdd, 0xcb, 0x85, 0x96, 0xf9, 0x7a,
	0xb9, 0x32, 0xf0, 0x40, 0xf8, 0xb7, 0x18, 0xc4, 0xe3, 0x15, 0x67, 0xfc, 0x67, 0xce, 0x7d, 0xe8,
	0x86, 0xe1, 0x5f, 0x4d, 0x7b, 0x00, 0xc4, 0x8d, 0x9a, 0xee, 0x7b, 0xac, 0x35, 0xf5, 0x36, 0xeb,
	0x51, 0x44, 0x8f, 0xa1, 0xd7, 0x58, 0x4d, 0x0f, 0xfc, 0x97, 0x4b, 0x43, 0xce, 0x6e, 0x5f, 0x42,
	0xfd, 0x3c, 0x1e, 0x02, 0x71, 0xbe, 0xd4, 0xe5, 0x5b, 0xae, 0x67, 0xb7, 0x5a, 0x48, 0x30, 0xed,
	0x55, 0xf2, 0xd9, 0x3d, 0x32, 0xd3, 0xae, 0x9f, 0xf7, 0xe3, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x12, 0x95, 0xa6, 0xb9, 0x7e, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StateClient is the client API for State service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StateClient interface {
	Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*Value, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Value, error)
	Delete(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Value, error)
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (State_ListClient, error)
	Rollback(ctx context.Context, in *RollbackRequest, opts ...grpc.CallOption) (*RollbackResult, error)
	Hash(ctx context.Context, in *HashRequest, opts ...grpc.CallOption) (*HashResponse, error)
}

type stateClient struct {
	cc *grpc.ClientConn
}

func NewStateClient(cc *grpc.ClientConn) StateClient {
	return &stateClient{cc}
}

func (c *stateClient) Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*Value, error) {
	out := new(Value)
	err := c.cc.Invoke(ctx, "/api.State/Set", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Value, error) {
	out := new(Value)
	err := c.cc.Invoke(ctx, "/api.State/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateClient) Delete(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Value, error) {
	out := new(Value)
	err := c.cc.Invoke(ctx, "/api.State/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (State_ListClient, error) {
	stream, err := c.cc.NewStream(ctx, &_State_serviceDesc.Streams[0], "/api.State/List", opts...)
	if err != nil {
		return nil, err
	}
	x := &stateListClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type State_ListClient interface {
	Recv() (*Value, error)
	grpc.ClientStream
}

type stateListClient struct {
	grpc.ClientStream
}

func (x *stateListClient) Recv() (*Value, error) {
	m := new(Value)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *stateClient) Rollback(ctx context.Context, in *RollbackRequest, opts ...grpc.CallOption) (*RollbackResult, error) {
	out := new(RollbackResult)
	err := c.cc.Invoke(ctx, "/api.State/Rollback", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateClient) Hash(ctx context.Context, in *HashRequest, opts ...grpc.CallOption) (*HashResponse, error) {
	out := new(HashResponse)
	err := c.cc.Invoke(ctx, "/api.State/Hash", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StateServer is the server API for State service.
type StateServer interface {
	Set(context.Context, *SetRequest) (*Value, error)
	Get(context.Context, *GetRequest) (*Value, error)
	Delete(context.Context, *GetRequest) (*Value, error)
	List(*ListRequest, State_ListServer) error
	Rollback(context.Context, *RollbackRequest) (*RollbackResult, error)
	Hash(context.Context, *HashRequest) (*HashResponse, error)
}

// UnimplementedStateServer can be embedded to have forward compatible implementations.
type UnimplementedStateServer struct {
}

func (*UnimplementedStateServer) Set(ctx context.Context, req *SetRequest) (*Value, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Set not implemented")
}
func (*UnimplementedStateServer) Get(ctx context.Context, req *GetRequest) (*Value, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedStateServer) Delete(ctx context.Context, req *GetRequest) (*Value, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedStateServer) List(req *ListRequest, srv State_ListServer) error {
	return status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedStateServer) Rollback(ctx context.Context, req *RollbackRequest) (*RollbackResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Rollback not implemented")
}
func (*UnimplementedStateServer) Hash(ctx context.Context, req *HashRequest) (*HashResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hash not implemented")
}

func RegisterStateServer(s *grpc.Server, srv StateServer) {
	s.RegisterService(&_State_serviceDesc, srv)
}

func _State_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.State/Set",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateServer).Set(ctx, req.(*SetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _State_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.State/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _State_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.State/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateServer).Delete(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _State_List_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StateServer).List(m, &stateListServer{stream})
}

type State_ListServer interface {
	Send(*Value) error
	grpc.ServerStream
}

type stateListServer struct {
	grpc.ServerStream
}

func (x *stateListServer) Send(m *Value) error {
	return x.ServerStream.SendMsg(m)
}

func _State_Rollback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateServer).Rollback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.State/Rollback",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateServer).Rollback(ctx, req.(*RollbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _State_Hash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateServer).Hash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.State/Hash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateServer).Hash(ctx, req.(*HashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _State_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.State",
	HandlerType: (*StateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Set",
			Handler:    _State_Set_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _State_Get_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _State_Delete_Handler,
		},
		{
			MethodName: "Rollback",
			Handler:    _State_Rollback_Handler,
		},
		{
			MethodName: "Hash",
			Handler:    _State_Hash_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "List",
			Handler:       _State_List_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "core.proto",
}
